# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Comparing Vector Elements to a Value
#' @description Internal function. It determines whether all the elements of a vector, eventually except the first one, are equal to a given value.
#' @usage permMin (X, B, truncTo)
#' @param X numeric vector
#' @param B length of \code{X}
#' @param truncTo numeric value
#' @author Anna Vesely
#' @return \code{permMin} returns \code{TRUE} if all elements of \code{X}, excluding the first one, are equal to \code{truncTo}, and returns \code{FALSE} otherwise.
#' @export
permMin <- function(X, B, truncTo) {
    .Call(`_sumSome_permMin`, X, B, truncTo)
}

rcpp_hello_world <- function() {
    .Call(`_sumSome_rcpp_hello_world`)
}

