# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Sign of Vector Elements
#' @description Internal function, called in \code{findCol}.
#' It determines whether all the elements of a vector are non-negative.
#' @usage allPos(X, B)
#' @param X numeric vector
#' @param B length of \code{X}
#' @author Anna Vesely
#' @return It returns \code{TRUE} if all elements of \code{X} are non-negative, and \code{FALSE} otherwise.
#' @noRd
NULL

#' @title Sign of Matrix Columns
#' @description Internal function, called in \code{cumulativeMatrices}.
#' Given a matrix where columns are in decreasing order, it finds the last column having no negative elements,
#' and the last column having at least one positive element.
#' @usage findCol(j1, j2, R, c, B)
#' @param j1 integer value, not smaller than the index of the last column of \code{R} having no negative elements
#' @param j2 integer value, not smaller than the index of the last column of \code{R} having at least one positive element
#' @param R numeric matrix
#' @param c number of columns in \code{R}
#' @param B number of rows in \code{R}
#' @author Anna Vesely
#' @return It updates the values of \code{j1} and \code{j2}, as the indices of the last columns of \code{R}
#' having no negative elements (\code{j1}) and containing at least one positive element (\code{j2}).
#' If such a column does not exist, the corresponding index is set to 0.
#' @examples
#' R <- matrix(c(rep(0,5), rep(1,4), rep(-1,1), rep(1,3), rep(-1,2), rep(1,2), rep(-1,3)), ncol=5, byrow=TRUE)
#' findCol(5, 5, R, 5, 4) # j1=2, j2=4
#' @noRd
NULL

#' @title Matrix of Cumulative Sums
#' @description Internal function, called in \code{buildMatrices}.
#' It updates a matrix of comulative sums.
#' @usage cumulativeMatrices(Asum, A, fixed, j1, j2, z, f, B, getJ)
#' @param Asum numeric matrix
#' @param A numeric matrix
#' @param fixed numeric vector
#' @param j1 integer value
#' @param j2 integer value
#' @param z number of selected columns
#' @param f number of columns in \code{A}
#' @param B number of rows in \code{A}
#' @param getJ boolean, \code{TRUE} to update indices
#' @author Anna Vesely
#' @return It sums by row \code{fixed} and the first \code{z} columns of \code{A}, then combines by row
#' the result and the remaining \code{f-z} columns of \code{A}.
#' \code{Asum} is updated as the corresponding matrix of cumulative sums.
#' If \code{getJ} is \code{TRUE}, then \code{j1} and \code{j2} are updated by applying \code{findCol}
#' to the remaining \code{f-z} columns of \code{A}.
#' @noRd
NULL

#' @title First Selected Elements
#' @description Internal function, called in \code{buildMatrices}.
#' It selects the first elements of a vector that do not exceed a given threshold.
#' @usage firstInS(z, s, X, f)
#' @param z number of selected elements
#' @param s integer threshold
#' @param X integer vector
#' @param f length of \code{X}
#' @author Anna Vesely
#' @return It returns a boolean vector of length \code{f}, where \code{TRUE} values correspond
#' to the first \code{z} elements of \code{X} that are not greater than \code{s}.
#' @noRd
NULL

#' @title Element Selection
#' @description Internal function, called in \code{buildMatrices}.
#' It selects the elements of a vector that appear in a second vector.
#' @usage selIndices (indices, X, H, f)
#' @param indices integer vector
#' @param X integer vector
#' @param H length of \code{indices}
#' @param f length of \code{X}
#' @author Anna Vesely
#' @return It returns a boolean vector of length \code{f}, where \code{TRUE} values correspond
#' to elements of \code{X} that appear in \code{indices}.
#' @noRd
NULL

#' @title Building Matrices
#' @description Internal function, called in \code{goLeft}, \code{goRight} and \code{checkTD}.
#' It updates the matrices that will be used in \code{checkTD} to apply the shortcut in a subspace.
#' @usage buildMatrices(Dsum, Rsum, D, I, R, fixed, j1, j2, z, s, f, f0, B, getDsum)
#' @param Dsum matrix of cumulative sums for the lower bound
#' @param Rsum matrix of cumulative sums for the upper bound
#' @param D matrix for the lower bound
#' @param I matrix of indices corresponding to elements in R
#' @param R matrix for the upper bound
#' @param fixed numeric vector, sum by row of fixed columns
#' @param j1 integer value
#' @param j2 integer value
#' @param z number of selected columns, equal to \code{s-TD+1}, where \code{TD} is a candidate value for the number of true discoveries
#' @param s size of the subset under closed testing
#' @param f number of non-fixed variables in the new subspace
#' @param f0 number of non-fixed variables in the current space
#' @param B number of transformations
#' @param getDsum boolean, \code{TRUE} to update \code{Dsum} and \code{D} 
#' @author Anna Vesely
#' @return It updates the matrices \code{Rsum}, \code{I} and \code{R} used to compute the upper bound
#' in the original space or a subspace generated by the branch and bound procedure.
#' It updates the indices \code{j1} and \code{j2} by applying \code{findCol} to \code{R}.
#' If \code{getDsum} is \code{TRUE}, it updates the matrices \code{Dsum} and \code{D} used to compute the lower bound.
#' @noRd
NULL

#' @title Creating Left Node by Removing Variable
#' @description Internal function, called in \code{checkTD}.
#' It generates a left node, i.e. a subspace obtained by removing a variable in the branch and bound procedure.
#' Moreover, it saves a list of elements characterizing the corresponding right node, obtained by fixing the variable.
#' @usage goLeft(vMin, vMax, Dsum, Rsum, D, I, R, fixed, fixedLast, j1, j2, z, s, f, B, lastFromS)
#' @param vMin minimum size to be checked
#' @param vMax maximum size to be checked
#' @param Dsum matrix of cumulative sums for the lower bound
#' @param Rsum matrix of cumulative sums for the upper bound
#' @param D matrix for the lower bound
#' @param I matrix of indices corresponding to elements in R
#' @param R matrix for the upper bound
#' @param fixed numeric vector, sum by row of fixed columns
#' @param fixedLast numeric vector, column fixed in the last step
#' @param j1 integer value
#' @param j2 integer value
#' @param z number of selected columns, equal to \code{s-TD+1}, where \code{TD} is a candidate value for the number of true discoveries
#' @param s size of the subset under closed testing
#' @param f number of non-fixed variables in the current space
#' @param B number of transformations
#' @param lastFromS boolean, \code{TRUE} if the removed variable is in the subset under closed testing
#' @author Anna Vesely
#' @return It updates \code{lastFromS}, the matrices \code{Rsum}, \code{I} and \code{R},
#' and the indices \code{j1} and \code{j2} in the new left subspace.
#' It returns a list containing the values of \code{z}, \code{vMin}, \code{vMax}, \code{fixed} and \code{f}
#' in the corresponding right subspace. 
#' @noRd
NULL

#' @title Creating Right Node by Fixing Variable
#' @description Internal function, called in \code{checkTD}.
#' It generates a right node, i.e. a subspace obtained by fixing a variable in the branch and bound procedure,
#' after closing the corresponding left node.
#' @usage goRight(Dsum, Rsum, D, I, R, fixed, fixedLast, j1, j2, z, s, f, B, lastFromS)
#' @param Dsum matrix of cumulative sums for the lower bound
#' @param Rsum matrix of cumulative sums for the upper bound
#' @param D matrix for the lower bound
#' @param I matrix of indices corresponding to elements in R
#' @param R matrix for the upper bound
#' @param fixed numeric vector, sum by row of fixed columns
#' @param fixedLast numeric vector, column fixed in the last step
#' @param j1 integer value
#' @param j2 integer value
#' @param z number of selected columns, equal to \code{s-TD+1}, where \code{TD} is a candidate value for the number of true discoveries
#' @param s size of the subset under closed testing
#' @param f number of non-fixed variables in the current space
#' @param B number of transformations
#' @param lastFromS boolean, \code{TRUE} if the fixed variable is in the subset under closed testing
#' @author Anna Vesely
#' @return It updates the matrices \code{Dsum}, \code{Rsum}, \code{D}, \code{I} and \code{R},
#' and the indices \code{j1} and \code{j2} in the new right subspace.
#' @noRd
NULL

#' @title Sign of Quantile
#' @description Internal function, called in \code{computeBounds}.
#' It determines whether the quantile of a vector is negative.
#' @usage Q(X, k, B)
#' @param X numeric vector
#' @param k integer value
#' @param B length of \code{X}
#' @author Anna Vesely
#' @return It returns \code{TRUE} if the \code{k}-th smallest element of \code{X} is negative, and \code{FALSE} otherwise.
#' @noRd
NULL

#' @title Shortcut
#' @description Internal function, called in \code{checkTD}.
#' It applies the shortcut, checking the bounds for a given collection of sizes.
#' @usage computeBounds(vMin, vMax, rej, indSizes, Dsum, Rsum, k, B, j1, j2, both)
#' @param vMin minimum size to be checked
#' @param vMax maximum size to be checked
#' @param rej boolean, \code{TRUE} if no non-rejection has been found
#' @param indSizes boolean, \code{TRUE} if the shortcut is unsure for some sizes
#' @param Dsum matrix of cumulative sums for the lower bound
#' @param Rsum matrix of cumulative sums for the upper bound
#' @param k integer value that determines the quantiles
#' @param B number of transformations
#' @param j1 integer value
#' @param j2 integer value
#' @param both boolean, \code{TRUE} to check both bounds, \code{FALSE} to check only the upper bound
#' @author Anna Vesely
#' @return It updates \code{rej} and \code{indSizes}, and eventually \code{vMin} and \code{vMax}.
#' A non-rejection corresponds to \code{rej=FALSE} and \code{indSizes=FALSE},
#' a rejection to \code{rej=TRUE} and \code{indSizes=FALSE}, and
#' an unsure outcome to \code{rej=TRUE} and \code{indSizes=TRUE}.
#' @noRd
NULL

#' @title Compare Vector Elements to Value
#' @description Internal function, called in \code{sumCt.internal}.
#' It determines whether all the elements of a vector, eventually except the first one, are equal to a given value.
#' @usage permMin(X, B, truncTo)
#' @param X numeric vector
#' @param B length of \code{X}
#' @param truncTo numeric value
#' @author Anna Vesely
#' @return It returns \code{TRUE} if all elements of \code{X}, excluding the first one, are equal to \code{truncTo}, and returns \code{FALSE} otherwise.
#' @keywords internal
permMin <- function(X, B, truncTo) {
    .Call(`_sumSome_permMin`, X, B, truncTo)
}

#' @title Check Candidate TD Value
#' @description Internal function, called in \code{bisectionTD}.
#' It checks whether a candidate value is a valid lower confidence bound for the number of true discoveries within a subset.
#' @usage checkTD(TD, D0, I0, R0, s, f0, k, B, BAB, nMax)
#' @param TD candidate value for the number of true discoveries
#' @param D0 matrix for the lower bound
#' @param I0 matrix of indices corresponding to elements in R0
#' @param R0 matrix for the upper bound
#' @param s size of the subset under closed testing
#' @param f0 number of variables
#' @param k integer value that determines the quantile
#' @param B number of transformations
#' @param BAB number of iterations
#' @param nMax maximum number of iterations
#' @author Anna Vesely
#' @return It returns a list containing \code{rej} (\code{TRUE} if no non-rejection was found),
#' \code{indSizes} (\code{TRUE} if the outcome is unsure) and \code{BAB} (number of iterations).
#' \code{TD} is a valid confidence lower bound when \code{rej=TRUE} and \code{indSizes=FALSE},
#' it is not when \code{rej=FALSE} and \code{indSizes=FALSE}, and
#' the outcome is unsure when \code{rej=TRUE} and \code{indSizes=TRUE}.
#' @keywords internal
checkTD <- function(TD, D0, I0, R0, s, f0, k, B, BAB, nMax) {
    .Call(`_sumSome_checkTD`, TD, D0, I0, R0, s, f0, k, B, BAB, nMax)
}

